### ISSUE TITLE
New Affiliate Program

### ISSUE THREAD

**Issue by dror-fine** [digital-marketing-engineer/software-engineer-affiliate-program-hub#13]
Hey :)

We've just launched Fine's affiliate program

- 30% of all subscriptions
- Temporary launch offer of 45% of subscriptions, for our first 40 affiliates only

[Here's more info](https://www.canva.com/design/DAGRGhtjlsY/zbISgLy9gp5BZTKiCEcfcg/view?utm_content=DAGRGhtjlsY&utm_campaign=designshare&utm_medium=link&utm_source=editor)

And [here's where you can check out Fine](https://fine.dev/?ref=ognaa_gh) 

Please let me know if suitable for the list in the AI category

**Comment by digital-marketing-engineer** [comment]
Thanks, fine.dev added as AI tool. Check [this commit](https://github.com/digital-marketing-engineer/software-engineer-affiliate-program-hub/commit/59db6812d628e6bc362875c630ab227f4c7f143e).

Will close this Github issue.
