### ISSUE TITLE
New affiliate program suggestions

### ISSUE THREAD

**Issue by vanani11** [digital-marketing-engineer/software-engineer-affiliate-program-hub#5]
Hey everyone, this affiliate program seems suitable for the list you have: https://kinsta.com/affiliates/
They offer recurring commissions for app & database hosting!

**Comment by digital-marketing-engineer** [comment]
Hello @vanani11 ,
Thanks for suggesting it.
I will put it under hosting

**Comment by digital-marketing-engineer** [comment]
Added!
